repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1 #latest release version
    hooks:
      - id: codespell
        args: [--config=.codespellrc]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: double-quote-string-fixer
      - id: no-commit-to-branch
        name: Do not use more than one slash in the branch name
        args: ['--pattern', '^[^/]*/[^/]*/']
      - id: no-commit-to-branch
        name: Do not use uppercase letters in the branch name
        args: ['--pattern', '^[^A-Z]*[A-Z]']
      - id: trailing-whitespace
        types_or: [c, c++]
